type Order {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    number: String!
    buyerId: String!
    buyer: User! @fetch(from: "buyerId" to:"id" anchor: true protocol: GRPC)
    goods: [Good!]! @map(from: "id" to: "orderId")
}

type Good {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    quantity: Int!
    orderId: Int!
    order: Order! @map(from: "orderId" to: "id" anchor: true)
    productId: Int!
    product: Product! @map(from: "productId" to: "id" anchor: true)
    merchantId: Int!
    merchant: Merchant! @map(from: "merchantId" to: "id" anchor: true)
}

type Product {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    name: String!
    price: Float!
}

type Merchant {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    name: String!
    organizationId: Int
    organization: Organization @fetch(from: "organizationId" to: "id" anchor: true protocol: GRPC)
    customerServices: [User!] @fetch(from: "organizationId" to: "organizationId" protocol: GRPC)
}