type User {
    id: ID @dataType(type: "Int" autoIncrement: true)
    login: String!
    password: String!
    name: String!
    age: Int
    disabled: Boolean
    sex: Sex
    userProfile: UserProfile @map(from: "id" to: "userId")
    organization: Organization @map(from: "organizationId" to: "id" anchor: true)
    roles: [Role!] @map(from: "id" with: {type: "UserRole" from: "userId" to: "roleId"} to: "id")
    mobileNumbers: [String!] @map(from: "id" with: {type: "UserMobileNumbers" from: "userId" to: "mobileNumber"})
}

type UserProfile {
    id: ID @dataType(type: "Int" autoIncrement: true)
    user: User @map(from: "userId" to: "id" anchor: true)
    email: String
    address: String
}

enum Sex {
    MAN
    FEMALE
}

type Role {
    id: ID @dataType(type: "Int" autoIncrement: true)
    name: String!
    type: [RoleType]! @map(from: "id" with: {type: "RoleRoleType" from: "roleId" to: "type"})
    users: [User!] @map(from: "id" with: {type: "UserRole" from: "roleId" to: "userId"} to: "id")
}

enum RoleType {
    ADMIN
    USER
    ANONYMOUS
}

type Organization {
    id: ID @dataType(type: "Int" autoIncrement: true)
    name: String!
    above: Organization @map(from: "aboveId" to: "id" anchor: true)
    users: [User!] @map(from: "id" to: "organizationId")
}