schema {
    query: QueryType
    mutation: MutationType
}

enum Operator {
    EQ
    LK
    GT
    GTE
    LT
    LTE
    NIL
}

enum Conditional {
    AND
    OR
}

directive @table(
    engine : String="InnoDB"
) on OBJECT

directive @column(
    default: String
    autoIncrement: Boolean
) on FIELD_DEFINITION

directive @dataType(
    type: String
    length: Int
    decimals: Int
) on FIELD_DEFINITION