!!io.graphoenix.spi.config.R2DBCConfig
driver: "mariadb"
host: "127.0.0.1"
port: 3306
user: "root"
password: "root"
database: "dev"
usePool: true
poolMaxSize: 20
poolMaxIdleTime: 1000
---
!!io.graphoenix.spi.config.JavaGeneratorConfig
basePackageName: "io.graphoenix.showcase.mysql.generated"
graphQLFileName: "auth.gql"