!!io.graphoenix.r2dbc.connector.config.ConnectionConfiguration
driver: "mariadb"
host: "127.0.0.1"
port: 3306
user: "root"
password: "root"
database: "dev"
usePool: true
poolMaxSize: 20
poolMaxIdleTime: 1000
