type User @table(engine: "InnoDB") {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    login: String!
    password: String!
    name: String!
    age: Int
    disable: Boolean
    sex: Sex
    userProfile: UserProfile @map(from: "id" to: "userId")
    rpcUserProfile: UserProfile @fetch(packageName: "io.graphoenix.showcase.mysql.grpc" from: "id" to: "userId" key:"id")
    organizationId: Int
    rpcOrganization: Organization @fetch(packageName: "io.graphoenix.showcase.mysql.grpc" from: "organizationId" to:"id" key:"id" anchor: true)
    organization: Organization @map(from: "organizationId" to: "id" anchor: true)
    roles: [Role!] @map(from: "id" with: {type: "UserRole" from: "userId" to: "roleId"} to: "id")
    phones: [String!] @map(from: "id" with: {type: "UserPhones" from: "userId" to: "phone"})
    test1: [Int!] @map(from: "id" with: {type: "UserTest1" from: "userId" to: "test1"})
    test2: [Boolean!] @map(from: "id" with: {type: "UserTest2" from: "userId" to: "test2"})
}

type UserProfile @table(engine: "InnoDB") {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    userId: String
    email: String
    address: String
    qq: String
    user: User @map(from: "userId" to: "id" anchor: true)
    rpcUser: User @fetch(packageName: "io.graphoenix.showcase.mysql.grpc" from: "userId" to: "id" key:"id" anchor: true)
}

type UserPhones @table(engine: "InnoDB") {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    userId: Int
    phone: String
}

type UserTest1 @table(engine: "InnoDB") {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    userId: Int
    test1: Int
}

type UserTest2 @table(engine: "InnoDB") {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    userId: Int
    test2: Boolean
}

enum Sex {
    MAN
    FEMALE
}

type UserRole @table(engine: "InnoDB") {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    userId: Int
    roleId: Int
}

type Role @table(engine: "InnoDB") {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    name: String!
    type: [RoleType]! @map(from: "id" with: {type: "RoleRoleType" from: "roleId" to: "type"})
    users: [User!] @map(from: "id" with: {type: "UserRole" from: "roleId" to: "userId"} to: "id")
}

enum RoleType {
    ADMIN
    USER
    ANONYMOUS
}

type RoleRoleType @table(engine: "InnoDB") {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    roleId: Int
    type: RoleType
}

type Organization @table(engine: "InnoDB") {
    id: ID @dataType(type: "int") @column(autoIncrement: true)
    aboveId: Int
    above: Organization @map(from: "aboveId" to: "id" anchor: true)
    users: [User!] @map(from: "id" to: "organizationId")
    rpcUsers: [User] @fetch(packageName: "io.graphoenix.showcase.mysql.grpc" from: "id" to: "organizationId" key:"id")
    name: String!
}