mutation introspection {
    __schema(
        types: [
            {
                name: "Role",
                kind: OBJECT,
                fields: [
                    {
                        name: "id",
                        type: {
                            kind: NON_NULL,
                            ofType: {
                                kind: SCALAR,
                                name: "ID",
                            },

                        },

                    },
                    {
                        name: "name",
                        type: {
                            kind: NON_NULL,
                            ofType: {
                                kind: SCALAR,
                                name: "String",
                            },

                        },

                    },
                    {
                        name: "users",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: NON_NULL,
                                ofType: {
                                    kind: OBJECT,
                                    name: "User",
                                },

                            },

                        },

                    }
                ],

            },
            {
                name: "User",
                kind: OBJECT,
                fields: [
                    {
                        name: "id",
                        type: {
                            kind: NON_NULL,
                            ofType: {
                                kind: SCALAR,
                                name: "ID",
                            },

                        },

                    },
                    {
                        name: "login",
                        type: {
                            kind: NON_NULL,
                            ofType: {
                                kind: SCALAR,
                                name: "String",
                            },

                        },

                    },
                    {
                        name: "password",
                        type: {
                            kind: NON_NULL,
                            ofType: {
                                kind: SCALAR,
                                name: "String",
                            },

                        },

                    },
                    {
                        name: "name",
                        type: {
                            kind: NON_NULL,
                            ofType: {
                                kind: SCALAR,
                                name: "String",
                            },

                        },

                    },
                    {
                        name: "age",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    },
                    {
                        name: "disable",
                        type: {
                            kind: SCALAR,
                            name: "Boolean",
                        },

                    },
                    {
                        name: "sex",
                        type: {
                            kind: ENUM,
                            name: "Sex",
                        },

                    },
                    {
                        name: "organizationId",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    },
                    {
                        name: "organization",
                        type: {
                            kind: OBJECT,
                            name: "Organization",
                        },

                    },
                    {
                        name: "roles",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: NON_NULL,
                                ofType: {
                                    kind: OBJECT,
                                    name: "Role",
                                },

                            },

                        },

                    }
                ],

            },
            {
                name: "Organization",
                kind: OBJECT,
                fields: [
                    {
                        name: "id",
                        type: {
                            kind: NON_NULL,
                            ofType: {
                                kind: SCALAR,
                                name: "ID",
                            },

                        },

                    },
                    {
                        name: "above_id",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    },
                    {
                        name: "users",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: NON_NULL,
                                ofType: {
                                    kind: OBJECT,
                                    name: "User",
                                },

                            },

                        },

                    },
                    {
                        name: "name",
                        type: {
                            kind: NON_NULL,
                            ofType: {
                                kind: SCALAR,
                                name: "String",
                            },

                        },

                    }
                ],

            },
            {
                name: "MutationType",
                kind: OBJECT,
                fields: [
                    {
                        name: "role",
                        type: {
                            kind: OBJECT,
                            name: "Role",
                        },

                    },
                    {
                        name: "user",
                        type: {
                            kind: OBJECT,
                            name: "User",
                        },

                    },
                    {
                        name: "organization",
                        type: {
                            kind: OBJECT,
                            name: "Organization",
                        },

                    },
                    {
                        name: "userrole",
                        type: {
                            kind: OBJECT,
                            name: "UserRole",
                        },

                    }
                ],

            },
            {
                name: "UserRole",
                kind: OBJECT,
                fields: [
                    {
                        name: "id",
                        type: {
                            kind: NON_NULL,
                            ofType: {
                                kind: SCALAR,
                                name: "ID",
                            },

                        },

                    },
                    {
                        name: "userId",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    },
                    {
                        name: "roleId",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    }
                ],

            },
            {
                name: "QueryType",
                kind: OBJECT,
                fields: [
                    {
                        name: "role",
                        type: {
                            kind: OBJECT,
                            name: "Role",
                        },

                    },
                    {
                        name: "roleList",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: OBJECT,
                                name: "Role",
                            },

                        },

                    },
                    {
                        name: "user",
                        type: {
                            kind: OBJECT,
                            name: "User",
                        },

                    },
                    {
                        name: "userList",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: OBJECT,
                                name: "User",
                            },

                        },

                    },
                    {
                        name: "organization",
                        type: {
                            kind: OBJECT,
                            name: "Organization",
                        },

                    },
                    {
                        name: "organizationList",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: OBJECT,
                                name: "Organization",
                            },

                        },

                    },
                    {
                        name: "userrole",
                        type: {
                            kind: OBJECT,
                            name: "UserRole",
                        },

                    },
                    {
                        name: "userroleList",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: OBJECT,
                                name: "UserRole",
                            },

                        },

                    }
                ],

            },
            {
                name: "Operator",
                kind: ENUM,
                enumValues: [
                    {
                        name: "EQ",
                    },
                    {
                        name: "NEQ",
                    },
                    {
                        name: "LK",
                    },
                    {
                        name: "NLK",
                    },
                    {
                        name: "GT",
                    },
                    {
                        name: "NLTE",
                    },
                    {
                        name: "GTE",
                    },
                    {
                        name: "NLT",
                    },
                    {
                        name: "LT",
                    },
                    {
                        name: "NGTE",
                    },
                    {
                        name: "LTE",
                    },
                    {
                        name: "NGT",
                    },
                    {
                        name: "NIL",
                    },
                    {
                        name: "NNIL",
                    }
                ],

            },
            {
                name: "Sex",
                kind: ENUM,
                enumValues: [
                    {
                        name: "MAN",
                    },
                    {
                        name: "FEMALE",
                    }
                ],

            },
            {
                name: "Conditional",
                kind: ENUM,
                enumValues: [
                    {
                        name: "AND",
                    },
                    {
                        name: "OR",
                    }
                ],

            },
            {
                name: "IDExpression",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "opr",
                        defaultValue: EQ,
                        type: {
                            kind: ENUM,
                            name: "Operator",
                        },

                    },
                    {
                        name: "val",
                        type: {
                            kind: SCALAR,
                            name: "ID",
                        },

                    },
                    {
                        name: "in",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: SCALAR,
                                name: "ID",
                            },

                        },

                    }
                ],

            },
            {
                name: "IntExpression",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "opr",
                        defaultValue: EQ,
                        type: {
                            kind: ENUM,
                            name: "Operator",
                        },

                    },
                    {
                        name: "val",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    },
                    {
                        name: "in",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: SCALAR,
                                name: "Int",
                            },

                        },

                    }
                ],

            },
            {
                name: "UserInput",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "id",
                        type: {
                            kind: SCALAR,
                            name: "ID",
                        },

                    },
                    {
                        name: "login",
                        type: {
                            kind: SCALAR,
                            name: "String",
                        },

                    },
                    {
                        name: "password",
                        type: {
                            kind: SCALAR,
                            name: "String",
                        },

                    },
                    {
                        name: "name",
                        type: {
                            kind: SCALAR,
                            name: "String",
                        },

                    },
                    {
                        name: "age",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    },
                    {
                        name: "disable",
                        type: {
                            kind: SCALAR,
                            name: "Boolean",
                        },

                    },
                    {
                        name: "sex",
                        type: {
                            kind: ENUM,
                            name: "Sex",
                        },

                    },
                    {
                        name: "organizationId",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    },
                    {
                        name: "organization",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "OrganizationInput",
                        },

                    }
                ],

            },
            {
                name: "FloatExpression",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "opr",
                        defaultValue: EQ,
                        type: {
                            kind: ENUM,
                            name: "Operator",
                        },

                    },
                    {
                        name: "val",
                        type: {
                            kind: SCALAR,
                            name: "Float",
                        },

                    },
                    {
                        name: "in",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: SCALAR,
                                name: "Float",
                            },

                        },

                    }
                ],

            },
            {
                name: "SexExpression",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "opr",
                        defaultValue: EQ,
                        type: {
                            kind: ENUM,
                            name: "Operator",
                        },

                    },
                    {
                        name: "val",
                        type: {
                            kind: ENUM,
                            name: "Sex",
                        },

                    },
                    {
                        name: "in",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: ENUM,
                                name: "Sex",
                            },

                        },

                    }
                ],

            },
            {
                name: "OrganizationExpression",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "cond",
                        defaultValue: AND,
                        type: {
                            kind: ENUM,
                            name: "Conditional",
                        },

                    },
                    {
                        name: "exs",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: INPUT_OBJECT,
                                name: "OrganizationExpression",
                            },

                        },

                    },
                    {
                        name: "id",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "IDExpression",
                        },

                    },
                    {
                        name: "above_id",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "IntExpression",
                        },

                    },
                    {
                        name: "above",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "OrganizationExpression",
                        },

                    },
                    {
                        name: "name",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "StringExpression",
                        },

                    }
                ],

            },
            {
                name: "UserRoleExpression",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "cond",
                        defaultValue: AND,
                        type: {
                            kind: ENUM,
                            name: "Conditional",
                        },

                    },
                    {
                        name: "exs",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: INPUT_OBJECT,
                                name: "UserRoleExpression",
                            },

                        },

                    },
                    {
                        name: "id",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "IDExpression",
                        },

                    },
                    {
                        name: "userId",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "IntExpression",
                        },

                    },
                    {
                        name: "roleId",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "IntExpression",
                        },

                    }
                ],

            },
            {
                name: "RoleInput",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "id",
                        type: {
                            kind: SCALAR,
                            name: "ID",
                        },

                    },
                    {
                        name: "name",
                        type: {
                            kind: SCALAR,
                            name: "String",
                        },

                    }
                ],

            },
            {
                name: "UserRoleInput",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "id",
                        type: {
                            kind: SCALAR,
                            name: "ID",
                        },

                    },
                    {
                        name: "userId",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    },
                    {
                        name: "roleId",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    }
                ],

            },
            {
                name: "StringExpression",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "opr",
                        defaultValue: EQ,
                        type: {
                            kind: ENUM,
                            name: "Operator",
                        },

                    },
                    {
                        name: "val",
                        type: {
                            kind: SCALAR,
                            name: "String",
                        },

                    },
                    {
                        name: "in",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: SCALAR,
                                name: "String",
                            },

                        },

                    }
                ],

            },
            {
                name: "UserExpression",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "cond",
                        defaultValue: AND,
                        type: {
                            kind: ENUM,
                            name: "Conditional",
                        },

                    },
                    {
                        name: "exs",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: INPUT_OBJECT,
                                name: "UserExpression",
                            },

                        },

                    },
                    {
                        name: "id",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "IDExpression",
                        },

                    },
                    {
                        name: "login",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "StringExpression",
                        },

                    },
                    {
                        name: "password",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "StringExpression",
                        },

                    },
                    {
                        name: "name",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "StringExpression",
                        },

                    },
                    {
                        name: "age",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "IntExpression",
                        },

                    },
                    {
                        name: "disable",
                        type: {
                            kind: SCALAR,
                            name: "Boolean",
                        },

                    },
                    {
                        name: "sex",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "SexExpression",
                        },

                    },
                    {
                        name: "organizationId",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "IntExpression",
                        },

                    },
                    {
                        name: "organization",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "OrganizationExpression",
                        },

                    }
                ],

            },
            {
                name: "RoleExpression",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "cond",
                        defaultValue: AND,
                        type: {
                            kind: ENUM,
                            name: "Conditional",
                        },

                    },
                    {
                        name: "exs",
                        type: {
                            kind: LIST,
                            ofType: {
                                kind: INPUT_OBJECT,
                                name: "RoleExpression",
                            },

                        },

                    },
                    {
                        name: "id",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "IDExpression",
                        },

                    },
                    {
                        name: "name",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "StringExpression",
                        },

                    }
                ],

            },
            {
                name: "MapWith",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "type",
                        type: {
                            kind: SCALAR,
                            name: "String",
                        },

                    },
                    {
                        name: "from",
                        type: {
                            kind: SCALAR,
                            name: "String",
                        },

                    },
                    {
                        name: "to",
                        type: {
                            kind: SCALAR,
                            name: "String",
                        },

                    }
                ],

            },
            {
                name: "OrganizationInput",
                kind: INPUT_OBJECT,
                inputFields: [
                    {
                        name: "id",
                        type: {
                            kind: SCALAR,
                            name: "ID",
                        },

                    },
                    {
                        name: "above_id",
                        type: {
                            kind: SCALAR,
                            name: "Int",
                        },

                    },
                    {
                        name: "above",
                        type: {
                            kind: INPUT_OBJECT,
                            name: "OrganizationInput",
                        },

                    },
                    {
                        name: "name",
                        type: {
                            kind: SCALAR,
                            name: "String",
                        },

                    }
                ],

            }
        ],

    ){
        types{
            name
        }
    }
}
