mutation introspection {
    __schema(
        types:  [
            {
                name: Role,
                kind: OBJECT,
                description: 1,
                fields: [
                {
                    name: id,
                    description: 1,
                    type:   {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: SCALAR,
                    name: ID,
                }
                }
            },
                {
                    name: name,
                    description: ,
                    type:   {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: SCALAR,
                    name: String,
                }
                }
            },
                {
                    name: users,
                    description: ,
                    type:   {
                    kind: LIST,
                    name: ,
                    ofType: {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: OBJECT,
                    name: User,
                }
                }
            }
            },
            ],
            enumValues: [
            ]
            inputFields: [
            ]
            },
            {
                name: User,
                kind: OBJECT,
                description: ,
                fields: [
                {
                    name: id,
                    description: ,
                    type:   {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: SCALAR,
                    name: ID,
                }
                }
            },
                {
                    name: login,
                    description: ,
                    type:   {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: SCALAR,
                    name: String,
                }
                }
            },
                {
                    name: password,
                    description: ,
                    type:   {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: SCALAR,
                    name: String,
                }
                }
            },
                {
                    name: name,
                    description: ,
                    type:   {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: SCALAR,
                    name: String,
                }
                }
            },
                {
                    name: age,
                    description: ,
                    type:   {
                    kind: SCALAR,
                    name: Int,
                }
                },
                {
                    name: disable,
                    description: ,
                    type:   {
                    kind: SCALAR,
                    name: Boolean,
                }
                },
                {
                    name: sex,
                    description: ,
                    type:   {
                    kind: ENUM,
                    name: Sex,
                }
                },
                {
                    name: organizationId,
                    description: ,
                    type:   {
                    kind: SCALAR,
                    name: Int,
                }
                },
                {
                    name: organization,
                    description: ,
                    type:   {
                    kind: OBJECT,
                    name: Organization,
                }
                },
                {
                    name: roles,
                    description: ,
                    type:   {
                    kind: LIST,
                    name: ,
                    ofType: {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: OBJECT,
                    name: Role,
                }
                }
            }
            },
            ],
            enumValues: [
            ]
            inputFields: [
            ]
            },
            {
                name: Organization,
                kind: OBJECT,
                description: ,
                fields: [
                {
                    name: id,
                    description: ,
                    type:   {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: SCALAR,
                    name: ID,
                }
                }
            },
                {
                    name: above_id,
                    description: ,
                    type:   {
                    kind: SCALAR,
                    name: Int,
                }
                },
                {
                    name: users,
                    description: ,
                    type:   {
                    kind: LIST,
                    name: ,
                    ofType: {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: OBJECT,
                    name: User,
                }
                }
            }
            },
                {
                    name: name,
                    description: ,
                    type:   {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: SCALAR,
                    name: String,
                }
                }
            },
            ],
            enumValues: [
            ]
            inputFields: [
            ]
            },
            {
                name: MutationType,
                kind: OBJECT,
                description: ,
                fields: [
                {
                    name: role,
                    description: ,
                    type:   {
                    kind: OBJECT,
                    name: Role,
                }
                },
                {
                    name: user,
                    description: ,
                    type:   {
                    kind: OBJECT,
                    name: User,
                }
                },
                {
                    name: organization,
                    description: ,
                    type:   {
                    kind: OBJECT,
                    name: Organization,
                }
                },
                {
                    name: userrole,
                    description: ,
                    type:   {
                    kind: OBJECT,
                    name: UserRole,
                }
                },
            ],
            enumValues: [
            ]
            inputFields: [
            ]
            },
            {
                name: UserRole,
                kind: OBJECT,
                description: ,
                fields: [
                {
                    name: id,
                    description: ,
                    type:   {
                    kind: NON_NULL,
                    name: ,
                    ofType: {
                    kind: SCALAR,
                    name: ID,
                }
                }
            },
                {
                    name: userId,
                    description: ,
                    type:   {
                    kind: SCALAR,
                    name: Int,
                }
                },
                {
                    name: roleId,
                    description: ,
                    type:   {
                    kind: SCALAR,
                    name: Int,
                }
                },
            ],
            enumValues: [
            ]
            inputFields: [
            ]
            },
            {
                name: QueryType,
                kind: OBJECT,
                description: ,
                fields: [
                {
                    name: role,
                    description: ,
                    type:   {
                    kind: OBJECT,
                    name: Role,
                }
                },
                {
                    name: roleList,
                    description: ,
                    type:   {
                    kind: LIST,
                    name: ,
                    ofType: {
                    kind: OBJECT,
                    name: Role,
                }
                }
            },
                {
                    name: user,
                    description: ,
                    type:   {
                    kind: OBJECT,
                    name: User,
                }
                },
                {
                    name: userList,
                    description: ,
                    type:   {
                    kind: LIST,
                    name: ,
                    ofType: {
                    kind: OBJECT,
                    name: User,
                }
                }
            },
                {
                    name: organization,
                    description: ,
                    type:   {
                    kind: OBJECT,
                    name: Organization,
                }
                },
                {
                    name: organizationList,
                    description: ,
                    type:   {
                    kind: LIST,
                    name: ,
                    ofType: {
                    kind: OBJECT,
                    name: Organization,
                }
                }
            },
                {
                    name: userrole,
                    description: ,
                    type:   {
                    kind: OBJECT,
                    name: UserRole,
                }
                },
                {
                    name: userroleList,
                    description: ,
                    type:   {
                    kind: LIST,
                    name: ,
                    ofType: {
                    kind: OBJECT,
                    name: UserRole,
                }
                }
            },
            ],
            enumValues: [
            ]
            inputFields: [
            ]
            },
            {
                name: Operator,
                kind: ENUM,
                description: ,
                fields: [
            ],
            enumValues: [
                {
                    name: EQ,
                    description:
                },
                {
                    name: NEQ,
                    description:
                },
                {
                    name: LK,
                    description:
                },
                {
                    name: NLK,
                    description:
                },
                {
                    name: GT,
                    description:
                },
                {
                    name: NLTE,
                    description:
                },
                {
                    name: GTE,
                    description:
                },
                {
                    name: NLT,
                    description:
                },
                {
                    name: LT,
                    description:
                },
                {
                    name: NGTE,
                    description:
                },
                {
                    name: LTE,
                    description:
                },
                {
                    name: NGT,
                    description:
                },
                {
                    name: NIL,
                    description:
                },
                {
                    name: NNIL,
                    description:
                },
            ]
            inputFields: [
            ]
            },
            {
                name: Sex,
                kind: ENUM,
                description: ,
                fields: [
            ],
            enumValues: [
                {
                    name: MAN,
                    description:
                },
                {
                    name: FEMALE,
                    description:
                },
            ]
            inputFields: [
            ]
            },
            {
                name: Conditional,
                kind: ENUM,
                description: ,
                fields: [
            ],
            enumValues: [
                {
                    name: AND,
                    description:
                },
                {
                    name: OR,
                    description:
                },
            ]
            inputFields: [
            ]
            },
            {
                name: IDExpression,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: opr,
                    description: ,
                    defaultValue: EQ,
                type:   {
                    kind: ENUM,
                    name: Operator,
                }
                },
                {
                    name: val,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: ID,
                    }
                },
                {
                    name: in,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: LIST,
                        name: ,
                        ofType: {
                    kind: SCALAR,
                    name: ID,
                }
                }
            },
            ]
            },
            {
                name: IntExpression,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: opr,
                    description: ,
                    defaultValue: EQ,
                type:   {
                    kind: ENUM,
                    name: Operator,
                }
                },
                {
                    name: val,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: Int,
                    }
                },
                {
                    name: in,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: LIST,
                        name: ,
                        ofType: {
                    kind: SCALAR,
                    name: Int,
                }
                }
            },
            ]
            },
            {
                name: UserInput,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: id,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: ID,
                    }
                },
                {
                    name: login,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: String,
                    }
                },
                {
                    name: password,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: String,
                    }
                },
                {
                    name: name,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: String,
                    }
                },
                {
                    name: age,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: Int,
                    }
                },
                {
                    name: disable,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: Boolean,
                    }
                },
                {
                    name: sex,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: ENUM,
                        name: Sex,
                    }
                },
                {
                    name: organizationId,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: Int,
                    }
                },
                {
                    name: organization,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: OrganizationInput,
                    }
                },
            ]
            },
            {
                name: FloatExpression,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: opr,
                    description: ,
                    defaultValue: EQ,
                type:   {
                    kind: ENUM,
                    name: Operator,
                }
                },
                {
                    name: val,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: Float,
                    }
                },
                {
                    name: in,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: LIST,
                        name: ,
                        ofType: {
                    kind: SCALAR,
                    name: Float,
                }
                }
            },
            ]
            },
            {
                name: SexExpression,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: opr,
                    description: ,
                    defaultValue: EQ,
                type:   {
                    kind: ENUM,
                    name: Operator,
                }
                },
                {
                    name: val,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: ENUM,
                        name: Sex,
                    }
                },
                {
                    name: in,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: LIST,
                        name: ,
                        ofType: {
                    kind: ENUM,
                    name: Sex,
                }
                }
            },
            ]
            },
            {
                name: OrganizationExpression,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: cond,
                    description: ,
                    defaultValue: AND,
                type:   {
                    kind: ENUM,
                    name: Conditional,
                }
                },
                {
                    name: exs,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: LIST,
                        name: ,
                        ofType: {
                    kind: INPUT_OBJECT,
                    name: OrganizationExpression,
                }
                }
            },
                {
                    name: id,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: IDExpression,
                    }
                },
                {
                    name: above_id,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: IntExpression,
                    }
                },
                {
                    name: above,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: OrganizationExpression,
                    }
                },
                {
                    name: name,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: StringExpression,
                    }
                },
            ]
            },
            {
                name: UserRoleExpression,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: cond,
                    description: ,
                    defaultValue: AND,
                type:   {
                    kind: ENUM,
                    name: Conditional,
                }
                },
                {
                    name: exs,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: LIST,
                        name: ,
                        ofType: {
                    kind: INPUT_OBJECT,
                    name: UserRoleExpression,
                }
                }
            },
                {
                    name: id,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: IDExpression,
                    }
                },
                {
                    name: userId,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: IntExpression,
                    }
                },
                {
                    name: roleId,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: IntExpression,
                    }
                },
            ]
            },
            {
                name: RoleInput,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: id,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: ID,
                    }
                },
                {
                    name: name,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: String,
                    }
                },
            ]
            },
            {
                name: UserRoleInput,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: id,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: ID,
                    }
                },
                {
                    name: userId,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: Int,
                    }
                },
                {
                    name: roleId,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: Int,
                    }
                },
            ]
            },
            {
                name: StringExpression,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: opr,
                    description: ,
                    defaultValue: EQ,
                type:   {
                    kind: ENUM,
                    name: Operator,
                }
                },
                {
                    name: val,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: String,
                    }
                },
                {
                    name: in,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: LIST,
                        name: ,
                        ofType: {
                    kind: SCALAR,
                    name: String,
                }
                }
            },
            ]
            },
            {
                name: UserExpression,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: cond,
                    description: ,
                    defaultValue: AND,
                type:   {
                    kind: ENUM,
                    name: Conditional,
                }
                },
                {
                    name: exs,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: LIST,
                        name: ,
                        ofType: {
                    kind: INPUT_OBJECT,
                    name: UserExpression,
                }
                }
            },
                {
                    name: id,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: IDExpression,
                    }
                },
                {
                    name: login,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: StringExpression,
                    }
                },
                {
                    name: password,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: StringExpression,
                    }
                },
                {
                    name: name,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: StringExpression,
                    }
                },
                {
                    name: age,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: IntExpression,
                    }
                },
                {
                    name: disable,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: Boolean,
                    }
                },
                {
                    name: sex,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: SexExpression,
                    }
                },
                {
                    name: organizationId,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: IntExpression,
                    }
                },
                {
                    name: organization,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: OrganizationExpression,
                    }
                },
            ]
            },
            {
                name: RoleExpression,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: cond,
                    description: ,
                    defaultValue: AND,
                type:   {
                    kind: ENUM,
                    name: Conditional,
                }
                },
                {
                    name: exs,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: LIST,
                        name: ,
                        ofType: {
                    kind: INPUT_OBJECT,
                    name: RoleExpression,
                }
                }
            },
                {
                    name: id,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: IDExpression,
                    }
                },
                {
                    name: name,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: StringExpression,
                    }
                },
            ]
            },
            {
                name: MapWith,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: type,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: String,
                    }
                },
                {
                    name: from,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: String,
                    }
                },
                {
                    name: to,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: String,
                    }
                },
            ]
            },
            {
                name: OrganizationInput,
                kind: INPUT_OBJECT,
                description: ,
                fields: [
            ],
            enumValues: [
            ]
            inputFields: [
                {
                    name: id,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: ID,
                    }
                },
                {
                    name: above_id,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: Int,
                    }
                },
                {
                    name: above,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: INPUT_OBJECT,
                        name: OrganizationInput,
                    }
                },
                {
                    name: name,
                    description: ,
                    defaultValue: ,
                    type:   {
                        kind: SCALAR,
                        name: String,
                    }
                },
            ]
            },
        ]
    ){
        types{
            name
        }
    }
}
